
language: python
python:
  - 3.7
install:
  - pip install -r requirements.txt
before_script:
  - python mysite/manage.py migrate
  - python mysite/manage.py collectstatic --noinput
script:
  - black --check .
  - flake8 .
  - coverage run --source='.' mysite/manage.py test
after_script:
  - coveralls
